import { ASSESSMENT_COMPLETED_STEPS, ASSESSMENT_STATUS, SELECT_WITH_SEARCH_DEFAULT_OPTIONS } from "@/constants"
import { UserPermissions } from "@/types"
import { formatDateUtil } from "@/utils"

import {
  IAssessmentInitialState,
  ISearchCommonDataInitialState,
  ITranslationInitialState,
  IUiInitialState,
  IUserInitialState,
} from "../types"

export const userInitialState: IUserInitialState = {
  isLoggedIn: false,
  userAppAccess: [],
  currentUser: {
    user: {
      id: 0,
      name: "",
      accountName: "",
      version: "1",
      fullName: "",
      email: "",
      surname: "",
      credit: 0,
      phone: null,
      phone2: null,
      fax: null,
      address: null,
      oldUsername: "",
      oldPassword: "",
      lastLoginDate: null,
      parentAccountId: "",
      lastPasswordChangeDate: null,
      isEmailRecipient: "",
      active: "",
      createdOn: null,
      lastModifiedOn: null,
      externalId: null,
      languageId: null,
      accountId: null,
      distributorId: null,
      creatorId: null,
      lastModifierId: null,
      organizationName: null,
      showOnReport: false,
      salesforceId: null,
      isAgreedTermOfUse: false,
      basicInfoOnly: false,
      firstLastName: false,
      notificationCount: 0,
      role: "" as any,
      distributor: {
        id: 0,
        label: "",
        value: "",
      },
      pricing: {
        id: 0,
        label: "",
        value: "",
      },
      language: {
        id: 0,
        label: "",
        value: "",
      },
      pricingSchemeId: "",
      paymentTypeId: "",
      paymentCurrencyId: "",
      amount: null,
      freeCredit: 0,
      tempAccess: false,
      tempDate: null,
      logoOnReport: false,
      defaultLang: SELECT_WITH_SEARCH_DEFAULT_OPTIONS,
      parentAccount: {
        id: 0,
        version: 0,
        name: "",
        role: "",
        credits: 0,
        creditsForCoachAdd: 0,
        viewSubTree: 0,
        active: 0,
        createdOn: "",
        lastModifiedOn: "",
        externalId: 0,
        parentAccountId: 0,
        creatorId: 0,
        lastModifierId: 0,
        salesforceId: "",
        paymentTypeId: 0,
        paymentCurrencyId: 0,
        lastModifierSSOId: "",
        amount: 0,
        pricingSchemeId: 0,
        companyId: null,
        freeCredit: 0,
        referentCount: 0,
        userName: "",
        pricingData: undefined,
        creditsAmount: "",
        organizationLogoUrl: "",
      },
      isTpProject: false,
      ssoId: "",
      pendingReqFreeCredits: 0,
      pendingReqRegularCredits: 0,
    },
    additionalData: {
      id: "",
      lastName: "",
      firstName: "",
      salutation: "",
      name: "",
      mailingStreet: "",
      email: "",
      title: "",
      department: undefined,
      certifications: [],
      region: "",
      countryCode: "",
      eQMiniDescription: undefined,
      language: [],
      mapAddress: undefined,
      certUsage: "",
      additionalNeedsAndNotes: undefined,
      mailingCountry: "",
      allyMembership: false,
      certProfilePhotoURL: "",
      company: "",
      country: "",
      state: undefined,
      certProfileVisibility: "",
      certRole: "",
      referrerFirstName: undefined,
      certProfileURL: undefined,
      certMiniBio: "",
      certLinkedInURL: "",
      certAllowEmailContact: false,
      certCognitoExists: false,
      certWalletURL: "",
      certSsoUuid: "",
      certKeywords: "",
      certRenewalAdmin: "",
      certStatus: "",
      certRenewalDate: "",
      certMapAddress: "",
      certCorrectionsRequested: undefined,
      certBio: "",
      certLanguages: "",
      certAreasOfWork: [],
      certMembership: "",
      latitude: "",
      certCurrentAceUnits: 0,
      certReach: undefined,
      certOfferToHelp: "",
      certNetworkLeaderInterest: "",
      certEQCoachingHours: 0,
      certICFStatus: "",
      certProfileLastConfirmed: "",
      longitude: "",
      peopleSupport: 0,
      donation: undefined,
      certLanguageId: "",
      certLastLogin: "",
      thiAcCredibleCertifications: "",
      thiCancelCertifications: false,
      thiCertExpiry: "",
      thiCourseIncomplete: undefined,
      thiIncompleteCertCount: undefined,
      thiCertStatus: "",
      userprofile: "",
      interFaceLang: "",
      uiInterFaceLang: "",
    },
  },
}

export const assessmentInitialState: IAssessmentInitialState = {
  assessmentDetails: {
    projectDetails: {
      id: 0,
      version: "",
      description: "",
      sendToTestTakerEmailText: null,
      sharedLink: "",
      name: "",
      hidden: "",
      startSendToTestTaker: null,
      startSendToCoach: null,
      startSendToOthers: null,
      currentCredits: "",
      maxCredits: "",
      stopForMaxCredits: "",
      projectType: "",
      oldSharedUsername: null,
      oldSharedPassword: null,
      itemsPerPage: 0,
      easyLoad: "",
      printCompanyName: "",
      special: "",
      sendAlsoTheLeadershipDevelopmentGuideToTestTaker: "",
      sendAlsoTheLeadershipDevelopmentGuideToCoach: "",
      sendAlsoTheLeadershipDevelopmentGuideToOthers: "",
      officialName: null,
      expireDate: "",
      personalDataMaxItems: "",
      maxQuestionnaires: 0,
      questionnairesCount: 0,
      active: false,
      createdOn: formatDateUtil(new Date(), "date"),
      lastModifiedOn: formatDateUtil(new Date(), "date"),
      externalId: "",
      ownerId: null,
      ownerName: "",
      reportLanguageId: "",
      reportNormId: "",
      itemLanguageId: "",
      creatorId: null,
      lastModifierId: null,
      deleted: "",
      companySize: "",
      sendReportsToTestTakerAnyway: false,
      allowDuplicateTestTakers: false,
      approval: 0,
      freeProject: false,
      isNewDocApiRequest: "",
      ownerIdSSO: "",
      lastModifierSSOId: null,
      reApproval: null,
      saveAssessToSalesforce: false,
      projectStartDate: null,
      status: "",
      isErichProject: "",
      isThePractice: "",
      isGSuitEnabled: "",
      isBasicInfoOnly: false,
      invitationsCount: 0,
      firstLastName: false,
      blockDuplicateAllTime: "",
      owner: {
        id: 0,
        label: "",
        fullName: "",
        email: "",
        role: "Coach",
      },
      companyLogoUrl: "",
      consultantLogoUrl: "",
      reportCount: 0,
      reportGeneration: {
        status: false,
        pending: [],
        isError: false,
      },
      isTpProject: false,
      customCompletionUrl: "",
      isPersonalDataQuestion: false,
    },
    invitation: [],
    projectReportOptions: {
      id: 0,
      name: "",
      description: "",
      credits: "",
    },
    projectType: "",
    emailReadonly: false,
    easyLoad: false,
    languageCode: "",
    assessmentData: undefined,
    instructions: [],
    itemLanguage: {
      id: 0,
      value: "",
      label: "",
    },
  },
  invitations: [],
  assessmentType: {
    type: undefined,
    id1: undefined,
    id2: undefined,
    tempTestTakerId: undefined,
    testTaker: undefined,
    testTakerTime: null,
  },
  selectedLanguage: {
    value: "",
    label: "",
  },
  status: ASSESSMENT_STATUS.none,
  completedStep: ASSESSMENT_COMPLETED_STEPS.started,
}

export const searchCommonDataInitialState: ISearchCommonDataInitialState = {
  isLoading: false,
  jobRole: { isLoading: false, data: [] },
  countries: { isLoading: false, data: [] },
  educations: { isLoading: false, data: [] },
  sector: { isLoading: false, data: [] },
  jobsFunctions: { isLoading: false, data: [] },
  norm: { isLoading: false, data: [] },
  language: { isLoading: false, data: [] },
  page: { isLoading: false, data: [] },
  projectType: { isLoading: false, data: [] },
  distributor: { isLoading: false, data: [] },
  coach: { isLoading: false, data: [] },
  pricing: { isLoading: false, data: [] },
  reportLanguages: { isLoading: false, data: [] },
  empRoles: { isLoading: false, data: [] },
}

export const translationInitialState: ITranslationInitialState = {
  languageData: {},
}

export const permissionsInitialState: UserPermissions = {
  routes: {
    canViewManageReports: false,
    canEditNorms: false,
    addEditPricing: false,
    canViewTransactionCreditHistory: false,
    canEditLangAndTrans: false,
    canEditEmailTemplates: false,
    canEditItemsTemplates: false,
    canEditAssessmentEditor: false,
    canCreateNewEditCoachesReferents: false,
    canAddEditDistributor: false,
    canViewConfigReport: false,
    canSeiProjects: false,
    canSeiGroup: false,
    canYvProject: false,
    canYvGroup: false,
    canProject360: false,
    canTvsProject: false,
    canOvsProject: false,
    canEvsProject: false,
    canLvsProject: false,
  },
  options: {
    canSearchReceivedRequest: false,
    canApproveCreditTransfer: false,
    canViewEditProjects: false,
    canCreateNewEditProfilers: false,
    canViewPeopleTracker: false,
    canDownloadFastData: false,
    canEditResources: false,
    canManageAdminFunctions: false,
    canViewEditProjectsMasterAccess: false,
    canViewManageReportsMasterAccess: false,
    canCreateNewEditProfilersMasterAccess: false,
    canCreateNewEditCoachesReferentsMasterAccess: false,
    canViewPeopleTrackerMasterAccess: false,
    canViewTransactionCreditHistoryMasterAccess: false,
    canOverrideInconsistentBlock: false,
    canDownloadSimpleList: false,
    canAddEditDistributorMasterAccess: false,
    canApproveFreeProject: false,
    canEditProjectOwner: false,
    canGrantRefunds: false,
    canApproveExtendFreeProjects: false,
    canDownloadFullData: false,
  },
}

export const uiInitialState: IUiInitialState = {
  globalLoader: false,
  isCreditReqLinkVisited: false,
  pagePerItm: 10,
  selectedInterFaceLanguage: {
    flag: "/images/us.png",
    label: "English (US)",
    value: "en-US",
    code: "en-US",
  },
  interFaceLanguagesList: [],
  isDesktopCollapsed: false,
}
